"""
App.py
This file will be auto-generated by code
"""
import asyncio
import uvloop
from typing import List, Callable
from navigator.applications import AppHandler

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

class Main(AppHandler):
  """Main Class.
  """
  _middleware: List = []
  auto_home: bool = True
  enable_notify: bool = False
  enable_static: bool = True

    def configure(self):
        super(Main, self).configure()

    async def on_startup(self, app):
        """
        on_startup.
        description: Signal for customize the response when server is started
        """
        pass

    async def on_shutdown(self, app):
        """
        on_shutdown.
        description: Signal for customize the response when server is shutting down
        """
        pass
