import asyncio
from typing import Any
from ..types import WebApp

class BaseApplication:
    def get_app(self) -> WebApp: ...
    def setup_app(self) -> WebApp: ...
    def event_loop(self) -> asyncio.AbstractEventLoop: ...
    def __setitem__(self, k, v) -> Any: ...
    def __getitem__(self, k) -> Any: ...
    def __repr__(self) -> str: ...
    def active_extensions(self) -> list: ...
    def setup(self) -> WebApp: ...
    def install_uvloop(self) -> None: ...
